#! /usr/bin/perl 

# qbox_to_xyz goes through a Qbox output file and prints out the atom coordinates in xyz
# format
#
# written by Erik Draeger, LLNL, 4/20/2007

sub print_usage {
  print "syntax:  qbox_to_xyz [Qbox output filename(s)]\n";
  return;
}

if ($#ARGV < 0) {
  print_usage();
  exit;
}

###  parse arguments for command-line options  ###
$firstarg = 0;
$argcnt = 0;
$optflag = 0;
while ($optflag == 0 && $argcnt <= $#ARGV) {
  $arg = $ARGV[$argcnt];
  if (substr($arg,0,1) eq '-') {
    $firstarg++;
    if ($arg eq '-v' || $arg eq '--verbose') {
      $verbose = 1;
    }
    elsif ($arg eq '-h' || $arg eq '--help') {
      print_usage();
      exit;
    }
    else {
      print "Unknown option:  $arg\n";
      print_usage();
      exit;
    }
  }
  else {
    $optflag = 1;
  }
  $argcnt++;
}

FILELOOP: foreach $outfile (@ARGV[$firstarg..$#ARGV]) {  

  if (! -e $outfile) {
    print "$outfile does not exist!\n";
    next FILELOOP;
  }

  open OUT, $outfile;
  $xyzfile = join '',$outfile,'.xyz';
  open XYZ, ">$xyzfile";
  $reading_coords = 0;
  $atcnt = 0;
  LINE: while ($line=<OUT>) {

    @testchar = split("#",$line);   # ignore comment lines
    if ($#testchar>0) { next LINE; }

    if ($line =~ /atom name/) { 
      $reading_coords = 1;
      @attmp = split '\"',$line;
      $atname = $attmp[1];
      @posline = split ' ',<OUT>;
      @velline = split ' ',<OUT>;
      @forline = split ' ',<OUT>;
      $tagcloseline = <OUT>;

      $atomname[$atcnt] = $atname;
      $posx[$atcnt] = $posline[1];
      $posy[$atcnt] = $posline[2];
      $posz[$atcnt] = $posline[3];

      $atcnt++;
    }
    else {
      if ($reading_coords == 1) {
        $reading_coords = 0;
        # print out last batch of coordinates to xyz file
        print XYZ "$atcnt\n\n";
        for ($i=0; $i<$atcnt; $i++) {
          $xyzname = $atomname[$i];
          while ($xyzname =~ /[0-9]/) {
            chop $xyzname;
          }
          printf XYZ " $xyzname  %10.6f  %10.6f  %10.6f\n",$posx[$i],$posy[$i],$posz[$i];
        }
        $atcnt = 0;
      }
    }

  }
  close OUT;
}
